jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          script: github.request('PUT /repos/${{github.repository}}/actions/workflows/workflow.yml/enable')
      - uses: actions/checkout@v2
      - name: step
        run: .github/workflows/workflow.sh
      - uses: actions/upload-artifact@v2
        with:
          if-no-files-found: error
          name: github-backup-MihaiB
          path: github-backup-MihaiB-*T*Z.tar.gz

name: workflow

'on':
  pull_request:
    branches: [master]
  push:
    branches: [master]
  schedule:
    # generated randomly
    - cron: '56 9 * * SAT'
