jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: step
        run: .github/workflows/workflow.sh
      - uses: actions/upload-artifact@v2
        with:
          path: github-backup-MihaiB-*T*Z.tar.gz
          if-no-files-found: error

name: workflow

'on':
  pull_request:
    branches: [master]
  push:
    branches: [master]
  schedule:
    # generated randomly
    - cron: '56 9 * * SAT'
